# Generated by Django 5.2.17 on 2026-08-06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("core", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="SessionEnrollment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("session", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="enrollments", to="core.classsession")),
                ("student", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="session_enrollments", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-joined_at"],
                "constraints": [models.UniqueConstraint(fields=("session", "student"), name="unique_session_enrollment")],
            },
        )
    ]
